/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CoProductList {
        /**
          * Path to data file
         */
        "dataPath": string;
        /**
          * Max number of columns
         */
        "maxNumberOfColumns": number;
    }
    interface CoProductListItem {
        /**
          * Description of product
         */
        "description": string;
        /**
          * Title of product
         */
        "productTitle": string;
        /**
          * Type of product
         */
        "type": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCoProductListElement extends Components.CoProductList, HTMLStencilElement {
    }
    var HTMLCoProductListElement: {
        prototype: HTMLCoProductListElement;
        new (): HTMLCoProductListElement;
    };
    interface HTMLCoProductListItemElement extends Components.CoProductListItem, HTMLStencilElement {
    }
    var HTMLCoProductListItemElement: {
        prototype: HTMLCoProductListItemElement;
        new (): HTMLCoProductListItemElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "co-product-list": HTMLCoProductListElement;
        "co-product-list-item": HTMLCoProductListItemElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CoProductList {
        /**
          * Path to data file
         */
        "dataPath"?: string;
        /**
          * Max number of columns
         */
        "maxNumberOfColumns"?: number;
    }
    interface CoProductListItem {
        /**
          * Description of product
         */
        "description"?: string;
        /**
          * Title of product
         */
        "productTitle"?: string;
        /**
          * Type of product
         */
        "type"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "co-product-list": CoProductList;
        "co-product-list-item": CoProductListItem;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "co-product-list": LocalJSX.CoProductList & JSXBase.HTMLAttributes<HTMLCoProductListElement>;
            "co-product-list-item": LocalJSX.CoProductListItem & JSXBase.HTMLAttributes<HTMLCoProductListItemElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
